"use strict";(function(){var
userAgent=navigator.userAgent.toLowerCase(),initialDate=new Date(),$document=$(document),$window=$(window),$html=$("html"),$body=$("body"),isDesktop=$html.hasClass("desktop"),isIE=userAgent.indexOf("msie")!==-1?parseInt(userAgent.split("msie")[1],10):userAgent.indexOf("trident")!==-1?11:userAgent.indexOf("edge")!==-1?12:false,isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),windowReady=false,isNoviBuilder=false,livedemo=true,plugins={bootstrapModal:$('.modal '),bootstrapTabs:$('.tabs-custom'),captcha:$('.recaptcha '),campaignMonitor:$('.campaign-mailform '),copyrightYear:$('.copyright-year '),materialParallax:$('.parallax-container '),mailchimp:$('.mailchimp-mailform '),owl:$('.owl-carousel '),preloader:$('.preloader '),rdNavbar:$('.rd-navbar '),rdMailForm:$('.rd-mailform '),rdInputLabel:$('.form-label '),regula:$('[data-constraints] '),slick:$('.slick-slider'),search:$('.rd-search '),wow:$('.wow '),parallaxJs:$('.parallax-scene'),swiper:document.querySelectorAll('.swiper-container '),counter:document.querySelectorAll('.counter '),multiToggles:document.querySelectorAll('[data-multitoggle] '),vide:$('.vide '),buttonNuka:$('.button-nuka '),customWaypoints:$('[data-custom-scroll-to]'),maps:document.querySelectorAll('.google-map-container'),countDown:$(".countdown"),particlesJs:$('.particles-js'),checkbox:$('input[type="checkbox"]'),selectFilter:$("select"),customToggle:$('[data-custom-toggle]'),video:document.querySelectorAll('video')};function isScrolledIntoView(elem){if(isNoviBuilder)return true;return elem.offset().top+elem.outerHeight()>=$window.scrollTop()&&elem.offset().top<=$window.scrollTop()+$window.height();}
function lazyInit(element,func){var scrollHandler=function(){if((!element.hasClass('lazy-loaded')&&(isScrolledIntoView(element)))){func.call(element);element.addClass('lazy-loaded');}};scrollHandler();$window.on('scroll',scrollHandler);}
$window.on('load',function(){if(plugins.preloader.length&&!isNoviBuilder){pageTransition({target:document.querySelector('.page'),delay:0,duration:500,classIn:'fadeIn',classOut:'fadeOut',classActive:'animated',conditions:function(event,link){return link&&!/(\#|javascript:void\(0\)|callto:|tel:|mailto:|:\/\/)/.test(link)&&!event.currentTarget.hasAttribute('data-lightgallery');},onTransitionStart:function(options){setTimeout(function(){plugins.preloader.removeClass('loaded');},options.duration*.75);},onReady:function(){plugins.preloader.addClass('loaded');windowReady=true;}});}
if(plugins.counter){for(let i=0;i<plugins.counter.length;i++){let
node=plugins.counter[i],counter=aCounter({node:node,duration:node.getAttribute('data-duration')||1000,formatter:node.hasAttribute('data-formatter')?function(value){return Number(value.toFixed()).toLocaleString(node.getAttribute('data-formatter'));}:null}),scrollHandler=(function(){if(Util.inViewport(this)&&!this.classList.contains('animated-first')){this.counter.run();this.classList.add('animated-first');}}).bind(node),blurHandler=(function(){this.counter.params.to=parseInt(this.textContent,10);this.counter.run();}).bind(node);if(isNoviBuilder){node.counter.run();node.addEventListener('blur',blurHandler);}else{scrollHandler();window.addEventListener('scroll',scrollHandler);}}}
if(plugins.materialParallax.length){if(!isNoviBuilder&&!isIE&&!isMobile){plugins.materialParallax.parallax();}else{for(var i=0;i<plugins.materialParallax.length;i++){var $parallax=$(plugins.materialParallax[i]);$parallax.addClass('parallax-disabled');$parallax.css({"background-image":'url('+$parallax.data("parallax-img")+')'});}}}});$(function(){isNoviBuilder=window.xMode;function toggleElementsVisibility(targets){for(var z=0;z<targets.length;z++){var hiddenElements=targets[z].querySelectorAll('[aria-hidden="true"]'),visibleElements=targets[z].querySelectorAll('[aria-hidden="false"]');for(var k=0;k<hiddenElements.length;k++){hiddenElements[k].setAttribute('aria-hidden','false');}
for(var k=0;k<visibleElements.length;k++){visibleElements[k].setAttribute('aria-hidden','true');}}}
function setRealPrevious(swiper){var element=swiper.$wrapperEl[0].children[swiper.activeIndex];swiper.realPrevious=Array.prototype.indexOf.call(element.parentNode.children,element);}
function setBackgrounds(swiper){let swiperSlides=swiper.el.querySelectorAll('[data-slide-bg]');for(let i=0;i<swiperSlides.length;i++){let swiperSlide=swiperSlides[i];swiperSlide.style.backgroundImage='url('+swiperSlide.getAttribute('data-slide-bg')+')';}}
function initCaptionAnimate(swiper){var
animate=function(caption){return function(){var duration;if(duration=caption.getAttribute('data-caption-duration'))caption.style.animationDuration=duration+'ms';caption.classList.remove('not-animated');caption.classList.add(caption.getAttribute('data-caption-animate'));caption.classList.add('animated');};},initializeAnimation=function(captions){for(var i=0;i<captions.length;i++){var caption=captions[i];caption.classList.remove('animated');caption.classList.remove(caption.getAttribute('data-caption-animate'));caption.classList.add('not-animated');}},finalizeAnimation=function(captions){for(var i=0;i<captions.length;i++){var caption=captions[i];if(caption.getAttribute('data-caption-delay')){setTimeout(animate(caption),Number(caption.getAttribute('data-caption-delay')));}else{animate(caption)();}}};swiper.params.caption={animationEvent:'slideChangeTransitionEnd'};initializeAnimation(swiper.$wrapperEl[0].querySelectorAll('[data-caption-animate]'));finalizeAnimation(swiper.$wrapperEl[0].children[swiper.activeIndex].querySelectorAll('[data-caption-animate]'));if(swiper.params.caption.animationEvent==='slideChangeTransitionEnd'){swiper.on(swiper.params.caption.animationEvent,function(){initializeAnimation(swiper.$wrapperEl[0].children[swiper.previousIndex].querySelectorAll('[data-caption-animate]'));finalizeAnimation(swiper.$wrapperEl[0].children[swiper.activeIndex].querySelectorAll('[data-caption-animate]'));});}else{swiper.on('slideChangeTransitionEnd',function(){initializeAnimation(swiper.$wrapperEl[0].children[swiper.previousIndex].querySelectorAll('[data-caption-animate]'));});swiper.on(swiper.params.caption.animationEvent,function(){finalizeAnimation(swiper.$wrapperEl[0].children[swiper.activeIndex].querySelectorAll('[data-caption-animate]'));});}}
function initOwlCarousel(carousel){var
aliaces=['-','-sm-','-md-','-lg-','-xl-','-xxl-'],values=[0,576,768,992,1200,1600],responsive={};for(var j=0;j<values.length;j++){responsive[values[j]]={};for(var k=j;k>=-1;k--){if(!responsive[values[j]]['items']&&carousel.attr('data'+aliaces[k]+'items')){responsive[values[j]]['items']=k<0?1:parseInt(carousel.attr('data'+aliaces[k]+'items'),10);}
if(!responsive[values[j]]['stagePadding']&&responsive[values[j]]['stagePadding']!==0&&carousel.attr('data'+aliaces[k]+'stage-padding')){responsive[values[j]]['stagePadding']=k<0?0:parseInt(carousel.attr('data'+aliaces[k]+'stage-padding'),10);}
if(!responsive[values[j]]['margin']&&responsive[values[j]]['margin']!==0&&carousel.attr('data'+aliaces[k]+'margin')){responsive[values[j]]['margin']=k<0?30:parseInt(carousel.attr('data'+aliaces[k]+'margin'),10);}}}
carousel.on('initialized.owl.carousel',function(){initLightGalleryItem(carousel.find('[data-lightgallery="item"]'),'lightGallery-in-carousel');});carousel.owlCarousel({autoplay:isNoviBuilder?false:carousel.attr('data-autoplay')!=='false',autoplayTimeout:carousel.attr("data-autoplay-time-out")?Number(carousel.attr("data-autoplay-time-out")):3000,smartSpeed:carousel.attr("data-smart-speed")?Number(carousel.attr("data-smart-speed")):250,autoplayHoverPause:carousel.attr("data-autoplay-hover-pause")==='true',URLhashListener:carousel.attr('data-hash-navigation')==='true'||false,startPosition:'URLHash',slideTransition:carousel.attr("data-slide-transition")?carousel.attr("data-slide-transition"):'',loop:isNoviBuilder?false:carousel.attr('data-loop')!=='false',items:1,autoHeight:carousel.attr('data-auto-height')==='true',center:carousel.attr('data-center')==='true',dotsContainer:carousel.attr('data-pagination-class')||false,navContainer:carousel.attr('data-navigation-class')||false,mouseDrag:isNoviBuilder?false:carousel.attr('data-mouse-drag')!=='false',nav:carousel.attr('data-nav')==='true',dots:carousel.attr('data-dots')==='true',dotsEach:carousel.attr('data-dots-each')?parseInt(carousel.attr('data-dots-each'),10):false,animateIn:carousel.attr('data-animation-in')?carousel.attr('data-animation-in'):false,animateOut:carousel.attr('data-animation-out')?carousel.attr('data-animation-out'):false,responsive:responsive,navText:carousel.attr('data-nav-text')?$.parseJSON(carousel.attr('data-nav-text')):[],navClass:carousel.attr('data-nav-class')?$.parseJSON(carousel.attr('data-nav-class')):['owl-prev','owl-next']});}
function attachFormValidator(elements){regula.custom({name:'PhoneNumber',defaultMessage:'Invalid phone number format',validator:function(){if(this.value==='')return true;else return /^(\+\d)?[0-9\-\(\) ]{5,}$/i.test(this.value);}});for(var i=0;i<elements.length;i++){var o=$(elements[i]),v;o.addClass("form-control-has-validation").after("<span class='form-validation'></span>");v=o.parent().find(".form-validation");if(v.is(":last-child"))o.addClass("form-control-last-child");}
elements.on('input change propertychange blur',function(e){var $this=$(this),results;if(e.type!=="blur")if(!$this.parent().hasClass("has-error"))return;if($this.parents('.rd-mailform').hasClass('success'))return;if((results=$this.regula('validate')).length){for(i=0;i<results.length;i++){$this.siblings(".form-validation").text(results[i].message).parent().addClass("has-error");}}else{$this.siblings(".form-validation").text("").parent().removeClass("has-error")}}).regula('bind');var regularConstraintsMessages=[{type:regula.Constraint.Required,newMessage:"The text field is required."},{type:regula.Constraint.Email,newMessage:"The email is not a valid email."},{type:regula.Constraint.Numeric,newMessage:"Only numbers are required"},{type:regula.Constraint.Selected,newMessage:"Please choose an option."}];for(var i=0;i<regularConstraintsMessages.length;i++){var regularConstraint=regularConstraintsMessages[i];regula.override({constraintType:regularConstraint.type,defaultMessage:regularConstraint.newMessage});}}
function isValidated(elements,captcha){var results,errors=0;if(elements.length){for(var j=0;j<elements.length;j++){var $input=$(elements[j]);if((results=$input.regula('validate')).length){for(k=0;k<results.length;k++){errors++;$input.siblings(".form-validation").text(results[k].message).parent().addClass("has-error");}}else{$input.siblings(".form-validation").text("").parent().removeClass("has-error")}}
if(captcha){if(captcha.length){return validateReCaptcha(captcha)&&errors===0}}
return errors===0;}
return true;}
function validateReCaptcha(captcha){var captchaToken=captcha.find('.g-recaptcha-response').val();if(captchaToken.length===0){captcha.siblings('.form-validation').html('Please, prove that you are not robot.').addClass('active');captcha.closest('.form-wrap').addClass('has-error');captcha.on('propertychange',function(){var $this=$(this),captchaToken=$this.find('.g-recaptcha-response').val();if(captchaToken.length>0){$this.closest('.form-wrap').removeClass('has-error');$this.siblings('.form-validation').removeClass('active').html('');$this.off('propertychange');}});return false;}
return true;}
window.onloadCaptchaCallback=function(){for(var i=0;i<plugins.captcha.length;i++){var
$captcha=$(plugins.captcha[i]),resizeHandler=(function(){var
frame=this.querySelector('iframe'),inner=this.firstElementChild,inner2=inner.firstElementChild,containerRect=null,frameRect=null,scale=null;inner2.style.transform='';inner.style.height='auto';inner.style.width='auto';containerRect=this.getBoundingClientRect();frameRect=frame.getBoundingClientRect();scale=containerRect.width/frameRect.width;if(scale<1){inner2.style.transform='scale('+scale+')';inner.style.height=(frameRect.height*scale)+'px';inner.style.width=(frameRect.width*scale)+'px';}}).bind(plugins.captcha[i]);grecaptcha.render($captcha.attr('id'),{sitekey:$captcha.attr('data-sitekey'),size:$captcha.attr('data-size')?$captcha.attr('data-size'):'normal',theme:$captcha.attr('data-theme')?$captcha.attr('data-theme'):'light',callback:function(){$('.recaptcha').trigger('propertychange');}});$captcha.after("<span class='form-validation'></span>");if(plugins.captcha[i].hasAttribute('data-auto-size')){resizeHandler();window.addEventListener('resize',resizeHandler);}}};function initLightGallery(itemsToInit,addClass){if(!isNoviBuilder){$(itemsToInit).lightGallery({thumbnail:$(itemsToInit).attr("data-lg-thumbnail")!=="false",selector:"[data-lightgallery='item']",autoplay:$(itemsToInit).attr("data-lg-autoplay")==="true",pause:parseInt($(itemsToInit).attr("data-lg-autoplay-delay"))||5000,addClass:addClass,mode:$(itemsToInit).attr("data-lg-animation")||"lg-slide",loop:$(itemsToInit).attr("data-lg-loop")!=="false"});}}
function initDynamicLightGallery(itemsToInit,addClass){if(!isNoviBuilder){$(itemsToInit).on("click",function(){$(itemsToInit).lightGallery({thumbnail:$(itemsToInit).attr("data-lg-thumbnail")!=="false",selector:"[data-lightgallery='item']",autoplay:$(itemsToInit).attr("data-lg-autoplay")==="true",pause:parseInt($(itemsToInit).attr("data-lg-autoplay-delay"))||5000,addClass:addClass,mode:$(itemsToInit).attr("data-lg-animation")||"lg-slide",loop:$(itemsToInit).attr("data-lg-loop")!=="false",dynamic:true,dynamicEl:JSON.parse($(itemsToInit).attr("data-lg-dynamic-elements"))||[]});});}}
function initLightGalleryItem(itemToInit,addClass){if(!isNoviBuilder){$(itemToInit).lightGallery({selector:"this",addClass:addClass,counter:false,youtubePlayerParams:{modestbranding:1,showinfo:0,rel:0,controls:0},vimeoPlayerParams:{byline:0,portrait:0}});}}
if(plugins.captcha.length){$.getScript("//www.google.com/recaptcha/api.js?onload=onloadCaptchaCallback&render=explicit&hl=en");}
if(navigator.platform.match(/(Mac)/i)){$html.addClass("mac-os");}
if(isIE){if(isIE===12)$html.addClass("ie-edge");if(isIE===11)$html.addClass("ie-11");if(isIE<10)$html.addClass("lt-ie-10");if(isIE<11)$html.addClass("ie-10");}
if(plugins.bootstrapModal.length){for(var i=0;i<plugins.bootstrapModal.length;i++){var modalItem=$(plugins.bootstrapModal[i]);modalItem.on('hidden.bs.modal',$.proxy(function(){var activeModal=$(this),rdVideoInside=activeModal.find('video'),youTubeVideoInside=activeModal.find('iframe');if(rdVideoInside.length){rdVideoInside[0].pause();}
if(youTubeVideoInside.length){var videoUrl=youTubeVideoInside.attr('src');youTubeVideoInside.attr('src','').attr('src',videoUrl);}},modalItem))}}
if(plugins.bootstrapTabs.length){for(let i=0;i<plugins.bootstrapTabs.length;i++){let bootstrapTab=$(plugins.bootstrapTabs[i]);let tabs=plugins.bootstrapTabs[i].querySelectorAll('.nav li a');for(let t=0;t<tabs.length;t++){var tab=tabs[t];tab.classList.remove('active');tab.addEventListener('click',function(event){event.preventDefault();$(this).tab('show');});}
$(tabs[0]).tab('show');}}
if(plugins.copyrightYear.length){plugins.copyrightYear.text(initialDate.getFullYear());}
if(isDesktop&&!isNoviBuilder){$().UItoTop({easingType:'easeOutQuad',containerClass:'ui-to-top fa fa-angle-up'});}
if(plugins.rdNavbar.length){var
navbar=plugins.rdNavbar,aliases={'-':0,'-sm-':576,'-md-':768,'-lg-':992,'-xl-':1200,'-xxl-':1600},responsive={};for(var alias in aliases){var link=responsive[aliases[alias]]={};if(navbar.attr('data'+alias+'layout'))link.layout=navbar.attr('data'+alias+'layout');if(navbar.attr('data'+alias+'device-layout'))link.deviceLayout=navbar.attr('data'+alias+'device-layout');if(navbar.attr('data'+alias+'hover-on'))link.focusOnHover=navbar.attr('data'+alias+'hover-on')==='true';if(navbar.attr('data'+alias+'auto-height'))link.autoHeight=navbar.attr('data'+alias+'auto-height')==='true';if(navbar.attr('data'+alias+'stick-up-offset'))link.stickUpOffset=navbar.attr('data'+alias+'stick-up-offset');if(navbar.attr('data'+alias+'stick-up'))link.stickUp=navbar.attr('data'+alias+'stick-up')==='true';if(isNoviBuilder)link.stickUp=false;else if(navbar.attr('data'+alias+'stick-up'))link.stickUp=navbar.attr('data'+alias+'stick-up')==='true';}
plugins.rdNavbar.RDNavbar({anchorNav:!isNoviBuilder,stickUpClone:(plugins.rdNavbar.attr("data-stick-up-clone")&&!isNoviBuilder)?plugins.rdNavbar.attr("data-stick-up-clone")==='true':false,responsive:responsive,callbacks:{onStuck:function(){var navbarSearch=this.$element.find('.rd-search input');if(navbarSearch){navbarSearch.val('').trigger('propertychange');}},onDropdownOver:function(){return!isNoviBuilder;},onUnstuck:function(){if(this.$clone===null)
return;var navbarSearch=this.$clone.find('.rd-search input');if(navbarSearch){navbarSearch.val('').trigger('propertychange');navbarSearch.trigger('blur');}}}});}
if(plugins.swiper.length){for(var i=0;i<plugins.swiper.length;i++){var
sliderMarkup=plugins.swiper[i],swiper,options={loop:sliderMarkup.getAttribute('data-loop')==='true'||false,effect:isIE?'slide':sliderMarkup.getAttribute('data-effect')||'slide',direction:sliderMarkup.getAttribute('data-direction')||'horizontal',speed:sliderMarkup.getAttribute('data-speed')?Number(sliderMarkup.getAttribute('data-speed')):1000,separateCaptions:sliderMarkup.getAttribute('data-separate-captions')==='true'||false,centeredSlides:sliderMarkup.getAttribute('data-centered-slides')==='true'||false,slidesPerView:sliderMarkup.getAttribute('data-slides-per-view')||1,initialSlide:sliderMarkup.getAttribute('data-initial-slide')||0,simulateTouch:sliderMarkup.getAttribute('data-simulate-touch')&&!isNoviBuilder?sliderMarkup.getAttribute('data-simulate-touch')==="true":false,coverflowEffect:{rotate:0,stretch:280,depth:80,slideShadows:false}};if(sliderMarkup.getAttribute('data-autoplay')){options.autoplay={delay:Number(sliderMarkup.getAttribute('data-autoplay'))||3000,stopOnLastSlide:false,disableOnInteraction:true,reverseDirection:false,};}
if(sliderMarkup.getAttribute('data-keyboard')==='true'){options.keyboard={enabled:sliderMarkup.getAttribute('data-keyboard')==='true',onlyInViewport:true};}
if(sliderMarkup.getAttribute('data-mousewheel')==='true'){options.mousewheel={releaseOnEdges:true,sensitivity:.1};}
if(sliderMarkup.querySelector('.swiper-button-next, .swiper-button-prev')){options.navigation={nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'};}
if(sliderMarkup.querySelector('.swiper-pagination')){options.pagination={el:'.swiper-pagination',type:'bullets',clickable:true};}
if(sliderMarkup.querySelector('.swiper-scrollbar')){options.scrollbar={el:'.swiper-scrollbar',hide:true,draggable:true};}
options.on={init:function(){setBackgrounds(this);setRealPrevious(this);initCaptionAnimate(this);this.on('slideChangeTransitionEnd',function(){setRealPrevious(this);});}};swiper=new Swiper(plugins.swiper[i],options);}}
if(plugins.owl.length){for(var i=0;i<plugins.owl.length;i++){var carousel=$(plugins.owl[i]);plugins.owl[i].owl=carousel;initOwlCarousel(carousel);}}
if($html.hasClass("wow-animation")&&plugins.wow.length&&!isNoviBuilder&&isDesktop){new WOW().init();}
if(plugins.rdInputLabel.length){plugins.rdInputLabel.RDInputLabel();}
if(plugins.regula.length){attachFormValidator(plugins.regula);}
if(plugins.mailchimp.length){for(i=0;i<plugins.mailchimp.length;i++){var $mailchimpItem=$(plugins.mailchimp[i]),$email=$mailchimpItem.find('input[type="email"]');$mailchimpItem.attr('novalidate','true');$email.attr('name','EMAIL');$mailchimpItem.on('submit',$.proxy(function($email,event){event.preventDefault();var $this=this;var data={},url=$this.attr('action').replace('/post?','/post-json?').concat('&c=?'),dataArray=$this.serializeArray(),$output=$("#"+$this.attr("data-form-output"));for(i=0;i<dataArray.length;i++){data[dataArray[i].name]=dataArray[i].value;}
$.ajax({data:data,url:url,dataType:'jsonp',error:function(resp,text){$output.html('Server error: '+text);setTimeout(function(){$output.removeClass("active");},4000);},success:function(resp){$output.html(resp.msg).addClass('active');$email[0].value='';var $label=$('[for="'+$email.attr('id')+'"]');if($label.length)$label.removeClass('focus not-empty');setTimeout(function(){$output.removeClass("active");},6000);},beforeSend:function(data){var isNoviBuilder=window.xMode;var isValidated=(function(){var results,errors=0;var elements=$this.find('[data-constraints]');var captcha=null;if(elements.length){for(var j=0;j<elements.length;j++){var $input=$(elements[j]);if((results=$input.regula('validate')).length){for(var k=0;k<results.length;k++){errors++;$input.siblings(".form-validation").text(results[k].message).parent().addClass("has-error");}}else{$input.siblings(".form-validation").text("").parent().removeClass("has-error")}}
if(captcha){if(captcha.length){return validateReCaptcha(captcha)&&errors===0}}
return errors===0;}
return true;})();if(isNoviBuilder||!isValidated)
return false;$output.html('Submitting...').addClass('active');}});return false;},$mailchimpItem,$email));}}
if(plugins.campaignMonitor.length){for(i=0;i<plugins.campaignMonitor.length;i++){var $campaignItem=$(plugins.campaignMonitor[i]);$campaignItem.on('submit',$.proxy(function(e){var data={},url=this.attr('action'),dataArray=this.serializeArray(),$output=$("#"+plugins.campaignMonitor.attr("data-form-output")),$this=$(this);for(i=0;i<dataArray.length;i++){data[dataArray[i].name]=dataArray[i].value;}
$.ajax({data:data,url:url,dataType:'jsonp',error:function(resp,text){$output.html('Server error: '+text);setTimeout(function(){$output.removeClass("active");},4000);},success:function(resp){$output.html(resp.Message).addClass('active');setTimeout(function(){$output.removeClass("active");},6000);},beforeSend:function(data){if(isNoviBuilder||!isValidated($this.find('[data-constraints]')))
return false;$output.html('Submitting...').addClass('active');}});var inputs=$this[0].getElementsByTagName('input');for(var i=0;i<inputs.length;i++){inputs[i].value='';var label=document.querySelector('[for="'+inputs[i].getAttribute('id')+'"]');if(label)label.classList.remove('focus','not-empty');}
return false;},$campaignItem));}}
if(plugins.rdMailForm.length){var i,j,k,msg={'MF000':'Successfully sent!','MF001':'Recipients are not set!','MF002':'Form will not work locally!','MF003':'Please, define email field in your form!','MF004':'Please, define type of your form!','MF254':'Something went wrong with PHPMailer!','MF255':'Aw, snap! Something went wrong.'};for(i=0;i<plugins.rdMailForm.length;i++){var $form=$(plugins.rdMailForm[i]),formHasCaptcha=false;$form.attr('novalidate','novalidate').ajaxForm({data:{"form-type":$form.attr("data-form-type")||"contact","counter":i},beforeSubmit:function(arr,$form,options){if(isNoviBuilder)
return;var form=$(plugins.rdMailForm[this.extraData.counter]),inputs=form.find("[data-constraints]"),output=$("#"+form.attr("data-form-output")),captcha=form.find('.recaptcha'),captchaFlag=true;output.removeClass("active error success");if(isValidated(inputs,captcha)){if(captcha.length){var captchaToken=captcha.find('.g-recaptcha-response').val(),captchaMsg={'CPT001':'Please, setup you "site key" and "secret key" of reCaptcha','CPT002':'Something wrong with google reCaptcha'};formHasCaptcha=true;$.ajax({method:"POST",url:"bat/reCaptcha.php",data:{'g-recaptcha-response':captchaToken},async:false}).done(function(responceCode){if(responceCode!=='CPT000'){if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle mdi mdi-check icon-xxs"></span><span>'+captchaMsg[responceCode]+'</span></p>')
setTimeout(function(){output.removeClass("active");},3500);captchaFlag=false;}else{output.html(captchaMsg[responceCode]);}
output.addClass("active");}});}
if(!captchaFlag){return false;}
form.addClass('form-in-process');if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa fa-circle-o-notch fa-spin icon-xxs"></span><span>Sending</span></p>');output.addClass("active");}}else{return false;}},error:function(result){if(isNoviBuilder)
return;var output=$("#"+$(plugins.rdMailForm[this.extraData.counter]).attr("data-form-output")),form=$(plugins.rdMailForm[this.extraData.counter]);output.text(msg[result]);form.removeClass('form-in-process');if(formHasCaptcha){grecaptcha.reset();}},success:function(result){if(isNoviBuilder)
return;var form=$(plugins.rdMailForm[this.extraData.counter]),output=$("#"+form.attr("data-form-output")),select=form.find('select');form.addClass('success').removeClass('form-in-process');if(formHasCaptcha){grecaptcha.reset();}
result=result.length===5?result:'MF255';output.text(msg[result]);if(result==="MF000"){if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle mdi mdi-check icon-xxs"></span><span>'+msg[result]+'</span></p>');}else{output.addClass("active success");}}else{if(output.hasClass("snackbars")){output.html(' <p class="snackbars-left"><span class="icon icon-xxs mdi mdi-alert-outline text-middle"></span><span>'+msg[result]+'</span></p>');}else{output.addClass("active error");}}
form.clearForm();if(select.length){select.select2("val","");}
form.find('input, textarea').trigger('blur');setTimeout(function(){output.removeClass("active error success");form.removeClass('success');},3500);}});}}
plugins.lightGallery=$('[data-lightgallery="group"]');if(plugins.lightGallery.length){for(var i=0;i<plugins.lightGallery.length;i++){initLightGallery(plugins.lightGallery[i]);}}
plugins.lightGalleryItem=$('[data-lightgallery="item"]');if(plugins.lightGalleryItem.length){for(var i=0;i<plugins.lightGalleryItem.length;i++){initLightGalleryItem(plugins.lightGalleryItem[i]);}}
plugins.lightDynamicGalleryItem=$('[data-lightgallery="dynamic"]');if(plugins.lightDynamicGalleryItem.length){for(var i=0;i<plugins.lightDynamicGalleryItem.length;i++){initDynamicLightGallery(plugins.lightDynamicGalleryItem[i]);}}
if(plugins.maps.length){let handler=function(){let
map=this.querySelector('.google-map'),markers=this.querySelectorAll('.google-map-markers li');let
defaults={node:map,center:this.hasAttribute('data-center')?this.getAttribute('data-center'):{lat:0,len:0},zoom:this.hasAttribute('data-zoom')?Number(this.getAttribute('data-zoom')):4,styles:this.hasAttribute('data-styles')?JSON.parse(this.getAttribute('data-styles')):null,markers:{},};for(let i=0;i<markers.length;i++){let node=markers[i];defaults.markers[Math.random().toString(36).substring(2)]={position:node.getAttribute('data-location'),html:node.getAttribute('data-description'),icon:node.hasAttribute('data-icon')?node.getAttribute('data-icon'):null};}
new SimpleGoogleMap(defaults);};$.getScript('//maps.google.com/maps/api/js?key=AIzaSyAja8QNd9DOcDkSXw81zPUnhEOzWGeBbnc&libraries=geometry,places&v=quarterly',function(){for(var i=0;i<plugins.maps.length;i++){let node=plugins.maps[i];if(node.hasAttribute('data-not-lazy')){handler.call(node);}else{lazyInit($(node),handler.bind(node));}}});}
if(plugins.multiToggles.length){for(var i=0;i<plugins.multiToggles.length;i++){var
node=plugins.multiToggles[i],toggle=new Toggle({node:node,targets:document.querySelectorAll(node.getAttribute('data-multitoggle')),scope:document.querySelectorAll(node.getAttribute('data-scope')),isolate:document.querySelectorAll(node.getAttribute('data-isolate'))});if(plugins.multiToggles[i].classList.contains('content-toggle')){node.addEventListener('click',function(){toggleElementsVisibility(this.mt.targets);});}}}
if(plugins.parallaxJs.length&&!isNoviBuilder){for(var i=0;i<plugins.parallaxJs.length;i++){var scene=plugins.parallaxJs[i];new Parallax(scene);}}
if(plugins.slick.length){for(var i=0;i<plugins.slick.length;i++){var $slickItem=$(plugins.slick[i]);$slickItem.on('init',function(slick){initLightGallery($('[data-lightgallery="group-slick"]'),'lightGallery-in-carousel');initLightGallery($('[data-lightgallery="item-slick"]'),'lightGallery-in-carousel');});$slickItem.slick({slidesToScroll:parseInt($slickItem.attr('data-slide-to-scroll'),10)||1,asNavFor:$slickItem.attr('data-for')||false,fade:true,dots:$slickItem.attr("data-dots")==="true",infinite:$slickItem.attr("data-loop")==="true",focusOnSelect:true,arrows:$slickItem.attr("data-arrows")==="true",swipe:$slickItem.attr("data-swipe")==="true",autoplay:isNoviBuilder?false:$slickItem.attr("data-autoplay")==="true",vertical:$slickItem.attr("data-vertical")==="true",centerMode:$slickItem.attr("data-center-mode")==="true",centerPadding:$slickItem.attr("data-center-padding")?$slickItem.attr("data-center-padding"):'0.50',mobileFirst:true,appendArrows:$slickItem.attr("data-arrows-class")||$slickItem,nextArrow:$slickItem.attr('data-custom-arrows')==="true"?'<button type="button" class="slick-next slick-button-static"></button>':'<button type="button" class="slick-next"></button>',prevArrow:$slickItem.attr('data-custom-arrows')==="true"?'<button type="button" class="slick-prev slick-button-static"></button>':'<button type="button" class="slick-prev"></button>',responsive:[{breakpoint:0,settings:{slidesToShow:parseInt($slickItem.attr('data-items'),10)||1}},{breakpoint:575,settings:{slidesToShow:parseInt($slickItem.attr('data-sm-items'),10)||1}},{breakpoint:767,settings:{slidesToShow:parseInt($slickItem.attr('data-md-items'),10)||1}},{breakpoint:991,settings:{slidesToShow:parseInt($slickItem.attr('data-lg-items'),10)||1}},{breakpoint:1199,settings:{slidesToShow:parseInt($slickItem.attr('data-xl-items'),10)||1}}]}).on('afterChange',function(event,slick,currentSlide,nextSlide){var $this=$(this),childCarousel=$this.attr('data-child');if(childCarousel){$(childCarousel+' .slick-slide').removeClass('slick-current');$(childCarousel+' .slick-slide').eq(currentSlide).addClass('slick-current');}});}}
if(plugins.vide.length){for(var i=0;i<plugins.vide.length;i++){var $element=$(plugins.vide[i]),options=$element.data('vide-options'),path=$element.data('vide-bg');$element.vide(path,options);var
videObj=$element.data('vide').getVideoObject(),scrollHandler=(function($element){if(isScrolledIntoView($element))this.play();else this.pause();}).bind(videObj,$element);scrollHandler();if(isNoviBuilder)videObj.pause();else document.addEventListener('scroll',scrollHandler);}}
if(plugins.buttonNuka.length){plugins.buttonNuka.on('mouseenter',function(e){var parentOffset=$(this).offset(),relX=e.pageX-parentOffset.left,relY=e.pageY-parentOffset.top;$(this).find('.button-overlay').css({top:relY,left:relX})}).on('mouseout',function(e){var parentOffset=$(this).offset(),relX=e.pageX-parentOffset.left,relY=e.pageY-parentOffset.top;$(this).find('.button-overlay').css({top:relY,left:relX})});}
if(plugins.customWaypoints.length&&!isNoviBuilder){var i;for(i=0;i<plugins.customWaypoints.length;i++){var $this=$(plugins.customWaypoints[i]);$this.on('click',function(e){e.preventDefault();$("body, html").stop().animate({scrollTop:$("#"+$(this).attr('data-custom-scroll-to')).offset().top},1000,function(){$window.trigger("resize");});});}}
if(plugins.countDown.length){for(var i=0;i<plugins.countDown.length;i++){var $countDownItem=$(plugins.countDown[i]),settings={format:$countDownItem.attr('data-format'),layout:$countDownItem.attr('data-layout')};if(livedemo){var d=new Date();d.setDate(d.getDate()+42);settings[$countDownItem.attr('data-type')]=d;}else{settings[$countDownItem.attr('data-type')]=new Date($countDownItem.attr('data-time'));}
$countDownItem.countdown(settings);}}
if(plugins.selectFilter.length){for(var i=0;i<plugins.selectFilter.length;i++){var select=$(plugins.selectFilter[i]);select.select2({dropdownParent:$('.page'),placeholder:select.attr('data-placeholder')||null,minimumResultsForSearch:select.attr('data-minimum-results-search')||Infinity,containerCssClass:select.attr('data-container-class')||null,dropdownCssClass:select.attr('data-dropdown-class')||null});}
if($("button[type='reset']").length){$("button[type='reset']").click(function(){plugins.selectFilter.val(null).trigger('change');});}}
if(plugins.checkbox.length){for(var i=0;i<plugins.checkbox.length;i++){$(plugins.checkbox[i]).addClass("checkbox-custom").after("<span class='checkbox-custom-dummy'></span>")}}
if(plugins.customToggle.length){for(var i=0;i<plugins.customToggle.length;i++){var $this=$(plugins.customToggle[i]);$this.on('click',$.proxy(function(event){event.preventDefault();var $ctx=$(this);$($ctx.attr('data-custom-toggle')).add(this).toggleClass('active');},$this));if($this.attr("data-custom-toggle-hide-on-blur")==="true"){$body.on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length&&e.data.find($(e.target)).length===0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}
if($this.attr("data-custom-toggle-disable-on-blur")==="true"){$body.on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length===0&&e.data.find($(e.target)).length===0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}}}
if(plugins.video.length){for(let i=0;i<plugins.video.length;i++){let node=plugins.video[i]
if(node.hasAttribute('data-video-play')){let button=document.querySelector(node.getAttribute('data-video-play'));if(button){node.controls=false;button.addEventListener('click',function(){if(node.paused){node.play();}else{node.pause();}});node.addEventListener('play',function(){button.classList.add('pause');button.classList.remove('play');this.controls=true;},false);node.addEventListener('pause',function(){button.classList.add('play');button.classList.remove('pause');},false);}}}}});if(plugins.particlesJs.length){if(plugins.particlesJs.attr('id')==='particles-js-1'){particlesJS("particles-js-1",{"particles":{"number":{"value":100,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"image","stroke":{"width":3,"color":"#fff"},"polygon":{"nb_sides":5},"image":{"src":"images/landing-christmas-04-50x50.png","width":100,"height":100}},"opacity":{"value":0.1,"random":true,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":5,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":50,"color":"#ffffff","opacity":0.6,"width":1},"move":{"enable":true,"speed":2,"direction":"bottom","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":300,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false},"onclick":{"enable":false},"resize":true}},"retina_detect":true});}
if(plugins.particlesJs.attr('id')==='particles-js-2'){particlesJS("particles-js-2",{"particles":{"number":{"value":100,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"image","stroke":{"width":3,"color":"#fff"},"polygon":{"nb_sides":5},"image":{"src":"images/landing-christmas-04-50x50.png","width":100,"height":100}},"opacity":{"value":0.1,"random":true,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":5,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":50,"color":"#ffffff","opacity":0.6,"width":1},"move":{"enable":true,"speed":2,"direction":"bottom","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":300,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false},"onclick":{"enable":false},"resize":true}},"retina_detect":true});}
if(plugins.particlesJs.attr('id')==='particles-js-3'){particlesJS("particles-js-3",{"particles":{"number":{"value":100,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"image","stroke":{"width":3,"color":"#fff"},"polygon":{"nb_sides":5},"image":{"src":"images/landing-christmas-04-50x50.png","width":100,"height":100}},"opacity":{"value":0.1,"random":true,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":5,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":50,"color":"#ffffff","opacity":0.6,"width":1},"move":{"enable":true,"speed":2,"direction":"bottom","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":300,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false},"onclick":{"enable":false},"resize":true}},"retina_detect":true});}
if(plugins.particlesJs.attr('id')==='particles-js-4'){particlesJS("particles-js-4",{"particles":{"number":{"value":100,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"image","stroke":{"width":3,"color":"#fff"},"polygon":{"nb_sides":5},"image":{"src":"images/landing-christmas-04-50x50.png","width":100,"height":100}},"opacity":{"value":0.1,"random":true,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":5,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":50,"color":"#ffffff","opacity":0.6,"width":1},"move":{"enable":true,"speed":2,"direction":"bottom","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":300,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false},"onclick":{"enable":false},"resize":true}},"retina_detect":true});}
if(plugins.particlesJs.attr('id')==='particles-js-5'){particlesJS("particles-js-5",{"particles":{"number":{"value":100,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"image","stroke":{"width":3,"color":"#fff"},"polygon":{"nb_sides":5},"image":{"src":"images/landing-christmas-04-50x50.png","width":100,"height":100}},"opacity":{"value":0.1,"random":true,"anim":{"enable":false,"speed":1,"opacity_min":0.1,"sync":false}},"size":{"value":5,"random":true,"anim":{"enable":false,"speed":20,"size_min":0.1,"sync":false}},"line_linked":{"enable":false,"distance":50,"color":"#ffffff","opacity":0.6,"width":1},"move":{"enable":true,"speed":2,"direction":"bottom","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":true,"rotateX":300,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false},"onclick":{"enable":false},"resize":true}},"retina_detect":true});}
if(plugins.particlesJs.attr('id')==='particles-js-6'){setTimeout(particlesJS,1000,"particles-js-6",{"particles":{"number":{"value":5,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"circle","stroke":{"width":0,"color":"#fff"},"polygon":{"nb_sides":6},"image":{"src":"img/github.svg","width":100,"height":100}},"opacity":{"value":0.3,"random":true,"anim":{"enable":false,"speed":10,"opacity_min":40,"sync":false}},"size":{"value":120,"random":true,"anim":{"enable":false,"speed":10,"size_min":40,"sync":false}},"line_linked":{"enable":false,"distance":200,"color":"#ffffff","opacity":1,"width":2},"move":{"enable":true,"speed":8,"direction":"none","random":false,"straight":false,"out_mode":"out","attract":{"enable":false,"rotateX":600,"rotateY":1200}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":true,"mode":"repulse"},"onclick":{"enable":true,"mode":"push"},"resize":true},"modes":{"grab":{"distance":400,"line_linked":{"opacity":1}},"bubble":{"distance":400,"size":40,"duration":2,"opacity":8,"speed":3},"repulse":{"distance":200},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":true});window.dispatchEvent(new CustomEvent('resize'));}}}());